# fly.toml app configuration file generated for ecfr-analyzer on 2026-04-04T22:57:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ecfr-analyzer'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  DB_PATH = '/data/ecfr.db'

[[mounts]]
  source = 'ecfr_data'
  destination = '/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
